### PR TITLE
added filename support in download

### LINKED ISSUE #1: Download filename not showing up
# When I open the URL where download is to be found, I get no filename or extension there, please make provision for that in you js code

Thanks

### PR DESCRIPTION
**Pull request by kyteinsky**
fixes #1 , small change

### CODE REVIEW

**Comment by akgsh** [comment]
I appreciate your commit. But I see a problem there. According to your commit, user will get a link like : **192.168.1.9:4700/filename.txt** . The problem with this is that if user opens this link, the file wont be downloaded because the route for downloading file is '/' and not '/filename.txt'

**Comment by kyteinsky** [comment]
Yes, I saw that sometime ago.
See if that issue is fixed now.

**Comment by akgsh** [comment]
Yeah, I think this will work. Can you attach the screenshot of what the link returns when we press share?
And have you tested it on your system?
I am updating the readme. I will add the steps on how to run the app on a local machine.

**Comment by kyteinsky** [comment]
Yeah I could do that but I don't have an installation of Nodejs currently, so it won't work for me now at least.
You could give it a try.

**Pull request closed without merging**
